config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get '/' => 'users#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login'  => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  delete 'logout' => 'sessions#destroy'
  get '/list' => 'courses#list'
  get '/clist' => 'registrations#list'
  resources :users
  resources :courses
  resources :registrations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	validates :name, presence: true, :uniqueness => true
	validates :credits, presence: true
	validates :admin, presence: true
end

app/models/registration.rb
class Registration < ApplicationRecord
	validates :c_id, presence: true
	validates :s_id, presence:true
	validates :c_id, :uniqueness => {:scope => :s_id}
	validates :grade, numericality: { only_integer: true, :less_than_or_equal_to => 10}
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :name, presence: true, :uniqueness => true
	validates :password, length: { in: 8..20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :require_user , :admin?, :student?

	def current_user 
	  @current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end

	def require_user 
	  redirect_to '/login' unless current_user 
	end

	def admin?
		if current_user
			current_user.type_of_users == "Admin"
		end
	end

	def student?
		if current_user
			current_user.type_of_users == "Student"
		end
	end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :logged_in?
  before_action :require_admin, only: [:new, :edit, :create, :update, :destroy, :list]

  def index
    @courses = Course.all
  end

  def show
    id = params[:id]
    @course = Course.find(id)
    @students = Registration.find_by_sql("SELECT * FROM Registrations WHERE c_id=#{id}")
  end

  def new
    @course = Course.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def list
    @courses = Course.find_by_sql(
        "SELECT * FROM COURSES WHERE admin = #{current_user.id}"
      )
  end

  def create
    @course = Course.new(course_params)
    @course.admin = current_user.id
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @course = Course.find(params[:id])
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :credits)
    end
 
  def require_admin
    unless admin?
      flash[:error] = "You must be admin to create a new course"
      redirect_to "/courses"
    end
  end

  def logged_in?
    if current_user.nil?
        redirect_to "/login"
      else
        current_user
      end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :logged_in?
  before_action :require_admin, only: [:edit,:update]

  def index
    @registrations = Registration.all
  end

  def show
    @registration = Registration.find(params[:id])
  end

  def new
    @registration = Registration.new
  end

  def edit
    @registration = Registration.find(params[:id])
  end

  def list
    @registrations = Registration.find_by_sql("SELECT * FROM REGISTRATIONS WHERE s_id = #{current_user.id}")
    @sum_of_credits = 0
    @total_sum = 0
    @registrations.each do |registration|
      unless registration.grade.nil?
        @sum_of_credits += Course.find(registration.c_id).credits
        @total_sum += (registration.grade)*(Course.find(registration.c_id).credits)
      end
    end
    @gpa = @total_sum.to_f/(@sum_of_credits.to_f)
  end

  def create
    @registration = Registration.new(create_params)
    @registration.s_id = current_user.id
    @registration.grade = nil
    respond_to do |format|
      if @registration.save
        format.html { redirect_to registrations_url, notice: 'Registration was successfully created.' }
        format.json { render :show, status: :created, location: @registration }
      else
        format.html { render :new }
        format.json { render json: @registration.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @registration = Registration.find(params[:id])
    respond_to do |format|
      if @registration.update(registration_params)
        format.html { redirect_to @registration, notice: 'Registration was successfully updated.' }
        format.json { render :show, status: :ok, location: @registration }
      else
        format.html { render :edit }
        format.json { render json: @registration.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @registration = Registration.find(params[:id])
    @registration.destroy
    respond_to do |format|
      format.html { redirect_to "/", notice: 'Course successfully dropped.' }
      format.json { head :no_content }
    end
  end

  private

    def set_registration
      @registration = Registration.find(params[:id])
    end

    def registration_params
      params.require(:registration).permit(:c_id, :grade)
    end

    def create_params
      params.permit(:c_id,:grade)
    end

    def logged_in?
      if current_user.nil?
        redirect_to "/login"
      else
        current_user
      end
    end

    def require_admin
      unless admin?
        flash[:error] = "You must be admin to create a new course"
        redirect_to "/courses"
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	@user = User.find_by_name(params[:session][:name])
	if @user && @user.authenticate(params[:session][:password])
		session[:user_id] = @user.id
		flash[:notice] = "You have successfully logged in."
		redirect_to '/'
	else
		flash[:notice] = "Wrong credentials"
	    redirect_to '/login'
	end 
  end

  def destroy 
	session[:user_id] = nil 
	flash[:notice] = "You have successfully logged out."
	redirect_to '/' 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def home

	end
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
	    if @user.save
	      session[:user_id] = @user.id
	      flash[:notice] = "User successfully created"
	      redirect_to '/'
	    else
	      flash[:notice] = "Username already exists"
	      redirect_to '/signup'
	    end
	end

	private

	def user_params
		params.require(:user).permit(:name, :type_of_users, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<% if @course.errors.any? %>
<div class="alert alert-danger">
  <h1>ERRORS IN CREATING A NEW COURSE</h1>
  <ul>
    <li>Check if all the required attributes are filled</li>
  </ul>
</div>
<ul>
  <% @course.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_with(model: course, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :credits %>
    <%= form.number_field :credits %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Courses</h1>
  
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Admin</th>
      <th>Credits</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= User.find(course.admin).name %></td>
        <td><%= course.credits %></td>
        <% if course.admin == current_user.id %>
          <td><%= link_to 'Show', course %></td>
          <td><%= link_to 'Edit', edit_course_path(course) %></td>
          <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin? %>
  <%= link_to 'New Course', new_course_path %>
<% else %>
  <%= link_to 'Your Courses', '/clist' %>
<% end %>

app/views/courses/list.html.erb
<h1>Your Courses</h1>
<% if admin? %>
  <%= link_to 'New Course', new_course_path %>
<% end %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Credits</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.credits %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "All Courses", :controller => "courses", :action => "index" %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>
<h2>
  <strong>Name:</strong>
  <%= @course.name %>
</h2>

<h2>
  <strong>Instructor in-charge:</strong>
  <%= User.find(@course.admin).name %>
</h2>

<h2>
  <strong>Credits:</strong>
  <%= @course.credits %>
</h2>

<br>

<% unless @students.nil? %>
	<h2>List of Students</h2>
  <ul>
  	<% @students.each do |student| %>
  		<li><h3><%= User.find(student.s_id).name %></h3></li>
  	<% end %>
<% else %>
	<h3>No students registered to this course</h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student Academic Portal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Student Academic Portal</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <% if student? %>
              <a class="nav-link" href="/clist">Courses</a>
            <% else %>
              <a class="nav-link" href="/list">Courses</a>
            <% end %>
          </li>
          <li class="nav-item">
            <% if student? %>
              <a class="nav-link" href="/registrations/new">Registration</a>
            <% else %>
              <a class="nav-link" href="/registrations">Registration</a>
            <% end %>
          </li>
          <% if current_user %>
            <a class="nav-link" href="/logout">Logout</a>
          <% else %>
            <% unless 
              current_page?(controller: 'sessions',action:'new')||
              current_page?(controller:'users',action:'new') %>
              <a class="nav-link" href="/login">Login</a>
              <br>
              <a class="nav-link" href="/signup">Sign Up</a>
            <% end %>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container" id="particles-js">
      <br>
      <% if notice %>
        <div class="alert alert-info" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <% if current_user %>
        <h1>Hi! there, <%= current_user.name %></h1>
      <% end %>

      <% if admin? %>
        <%= link_to "My courses", :controller => "courses", :action => "list" %>
      <% else %>
        <% if student? %>
          
        <% end %>
      <% end %>
      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

app/views/users/home.html.erb
<h1>Hi there,<br>
Welcome to SAP</h1>
<p>
	
</p>
<% if current_user %>
	
<% end %>
<% if student? %>
	<%= link_to "Your Courses", :controller => "registrations", :action => "list" %>
<% elsif admin? %>
	
<% end %>
	

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>  
  <%= f.text_field :name, :placeholder => "Name(Unique Username)" %> 
  <%= f.password_field :password, :placeholder => "Password(min 8 characters)" %> 
  <%= f.select :type_of_users, ['Student', 'Admin']%>
  <%= f.submit "Signup", class: "btn-submit" %>
<% end %>